image: node:latest
stages:
  - build-test

e2e:firefox:
  stage: confidence-check
  services:
    - selenium/standalone-firefox
  script:
    - npm run confidence-check --host=http://selenium:4444/wd/hub
e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - npm run confidence-check --host=http://selenium:4444/wd/hub

local_integration_test:
  stage: build-test  
  script:
    - npm install
    - node server.js &
    - npm test