default:
  image: node:16

stages:
  - build-test

e2e:firefox:
  stage: testwdio
  before_script:
    - cd wdioTests
  services:
    - selenium/standalone-firefox:latest
  script:
    - npm install
    - npm run testwdio --host=selenium__standalone-firefox


local_integration_test:
  stage: build-test  
  script:
    - yarn install
    - yarn test
    
 