default:
  image: node:16

variables:
   HUB_PORT_4444_TCP_ADDR: "selenium__hub"
   HUB_PORT_4444_TCP_PORT: "4444"
services:
   - selenium/hub:latest
   - selenium/node-phantomjs:latest

stages:
  - build-test

local_integration_test:
  stage: build-test  
  script:
    - yarn install
    - yarn test
    
 