
image: node:16

services:
  - selenium/standalone-chrome:latest

variables:
  SELENIUM_URL: "http://selenium__standalone-chrome:4444/wd/hub"

stages:
  - build-test

local_integration_test:
  stage: build-test  
  script:
    - npm install
    - npm test
    
 