image: node:latest

variables:
  selenium_remote_url: "http://gitlab-selenium-server:4444/wd/hub"

stages:
  - build-test
  
local_integration_test:
  stage: build-test  
  script:
    - npm install
    - node server.js &
    - npm test