image: node:latest

stages:
  - build-test
services:
  - selenium/standalone-chrome
  
local_integration_test:
  stage: build-test  
  script:
    - npm run confidence-check --host=selenium__standalone-chrome
    - npm install
    - npm test
    
 