default:
  image: node:16

variables:
   HUB_PORT_4444_TCP_ADDR: "selenium__hub"
   HUB_PORT_4444_TCP_PORT: "4444"
services:
   - selenium/hub:latest
   - selenium/node-phantomjs:latest

stages:
   - test
test:
   stage: test
   before_script:
     - apt-get update
     - apt-get install -y default-jdk default-jre
     - node ./node_modules/protractor/bin/webdriver-manager update
   script:
     - ./node_modules/.bin/protractor protractor.ci.conf.js
     - npm install
     - npm test
    
 