default:
  image: node:16

stages:
  - build-test

Regression_Suite:
     stage: test
     tags:
       - selenium
     script:
       - echo "Env = $env",  "Suite = $suite" , "Browser = $browser"
       - mvn clean install -Denv="$env" -Dsuite="$suite"

local_integration_test:
  stage: build-test  
  script:
    - yarn install
    - yarn test
    
 