default:
  image: node:16

stages:
  - build-test

services:
    - name: selenium/standalone-chrome:latest
    - name: selenium/standalone-firefox:latest

variables:
  ACCEPT_EULA: Y
  SA_PASSWORD: test
  MSSQL_DB: test
  MSSQL_USER: test
  MSSQL_PASSWORD: test
  p: -4444:4444



before_script:
  - apt-get update && apt-get install -y gnupg2
  - apt-get install gnupg

  # Install Chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  - apt install -y ./google-chrome-stable_current_amd64.deb
  # Install Firefox
  - apt-get install -y firefox-esr
  - apt install chromium-chromedriver


local_integration_test:
  stage: build-test  
  script:
    - npm install
    - npm test
    
 