default:
  image: node:16

stages:
  - build-test

services:
    - name: selenium/standalone-chrome:latest
    - name: selenium/standalone-firefox:latest

variables:
  selenium_port: 4444
  selenium_host: "http://selenium:4444/wd/hub"
  ports: -4444:4444


local_integration_test:
  stage: build-test  
  script:
    - npm install
    - npm test
    
 